// api/aisfc-2024.js
// Simple Vercel serverless function with mock All-Ireland SFC data

module.exports = (req, res) => {
  const matches = [
    {
      id: 1,
      date: '2024-06-29',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Kerry',
      away_team: 'Derry',
      home_goals: 0,
      home_points: 15,
      away_goals: 1,
      away_points: 11,
    },
    {
      id: 2,
      date: '2024-06-30',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Donegal',
      away_team: 'Louth',
      home_goals: 1,
      home_points: 23,
      away_goals: 0,
      away_points: 18,
    },
    {
      id: 3,
      date: '2024-06-30',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Dublin',
      away_team: 'Galway',
      home_goals: 2,
      home_points: 17,
      away_goals: 0,
      away_points: 14,
    },
    {
      id: 4,
      date: '2024-06-29',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Armagh',
      away_team: 'Roscommon',
      home_goals: 2,
      home_points: 12,
      away_goals: 0,
      away_points: 12,
    },
    {
      id: 5,
      date: '2024-07-13',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Armagh',
      away_team: 'Kerry',
      home_goals: 0,
      home_points: 17,
      away_goals: 2,
      away_points: 10,
    },
    {
      id: 6,
      date: '2024-07-14',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Dublin',
      away_team: 'Donegal',
      home_goals: 1,
      home_points: 15,
      away_goals: 0,
      away_points: 16,
    },
    {
      id: 7,
      date: '2024-07-28',
      competition: 'All-Ireland SFC',
      venue: 'Croke Park',
      home_team: 'Armagh',
      away_team: 'Dublin',
      home_goals: 1,
      home_points: 13,
      away_goals: 1,
      away_points: 12,
    },
  ];

  res.setHeader('Content-Type', 'application/json');
  res.status(200).json({ matches });
};
